# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import federation_pb2 as federation__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in federation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederationCoordinatorStub:
    """Service gRPC du coordinateur d'apprentissage fédéré
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClient = channel.unary_unary(
                '/federation.FederationCoordinator/RegisterClient',
                request_serializer=federation__pb2.RegisterRequest.SerializeToString,
                response_deserializer=federation__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/federation.FederationCoordinator/Heartbeat',
                request_serializer=federation__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=federation__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.RequestMutualExclusion = channel.unary_unary(
                '/federation.FederationCoordinator/RequestMutualExclusion',
                request_serializer=federation__pb2.MutexRequest.SerializeToString,
                response_deserializer=federation__pb2.MutexResponse.FromString,
                _registered_method=True)
        self.ReleaseMutualExclusion = channel.unary_unary(
                '/federation.FederationCoordinator/ReleaseMutualExclusion',
                request_serializer=federation__pb2.MutexRelease.SerializeToString,
                response_deserializer=federation__pb2.MutexAck.FromString,
                _registered_method=True)
        self.ResolveName = channel.unary_unary(
                '/federation.FederationCoordinator/ResolveName',
                request_serializer=federation__pb2.NameResolveRequest.SerializeToString,
                response_deserializer=federation__pb2.NameResolveResponse.FromString,
                _registered_method=True)
        self.QueryByAttributes = channel.unary_unary(
                '/federation.FederationCoordinator/QueryByAttributes',
                request_serializer=federation__pb2.AttributeQueryRequest.SerializeToString,
                response_deserializer=federation__pb2.AttributeQueryResponse.FromString,
                _registered_method=True)
        self.UploadGradients = channel.stream_unary(
                '/federation.FederationCoordinator/UploadGradients',
                request_serializer=federation__pb2.GradientChunk.SerializeToString,
                response_deserializer=federation__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.DownloadModel = channel.unary_stream(
                '/federation.FederationCoordinator/DownloadModel',
                request_serializer=federation__pb2.ModelRequest.SerializeToString,
                response_deserializer=federation__pb2.ModelChunk.FromString,
                _registered_method=True)
        self.SendElection = channel.unary_unary(
                '/federation.FederationCoordinator/SendElection',
                request_serializer=federation__pb2.ElectionMessage.SerializeToString,
                response_deserializer=federation__pb2.ElectionResponse.FromString,
                _registered_method=True)
        self.AnnounceCoordinator = channel.unary_unary(
                '/federation.FederationCoordinator/AnnounceCoordinator',
                request_serializer=federation__pb2.CoordinatorMessage.SerializeToString,
                response_deserializer=federation__pb2.CoordinatorAck.FromString,
                _registered_method=True)


class FederationCoordinatorServicer:
    """Service gRPC du coordinateur d'apprentissage fédéré
    """

    def RegisterClient(self, request, context):
        """RPC unary : petits messages (heartbeat, registration)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestMutualExclusion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseMutualExclusion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryByAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadGradients(self, request_iterator, context):
        """RPC streaming : gros volumes (gradients/modèles)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendElection(self, request, context):
        """Élection de leader (Bully)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnounceCoordinator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederationCoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=federation__pb2.RegisterRequest.FromString,
                    response_serializer=federation__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=federation__pb2.HeartbeatRequest.FromString,
                    response_serializer=federation__pb2.HeartbeatResponse.SerializeToString,
            ),
            'RequestMutualExclusion': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestMutualExclusion,
                    request_deserializer=federation__pb2.MutexRequest.FromString,
                    response_serializer=federation__pb2.MutexResponse.SerializeToString,
            ),
            'ReleaseMutualExclusion': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseMutualExclusion,
                    request_deserializer=federation__pb2.MutexRelease.FromString,
                    response_serializer=federation__pb2.MutexAck.SerializeToString,
            ),
            'ResolveName': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveName,
                    request_deserializer=federation__pb2.NameResolveRequest.FromString,
                    response_serializer=federation__pb2.NameResolveResponse.SerializeToString,
            ),
            'QueryByAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryByAttributes,
                    request_deserializer=federation__pb2.AttributeQueryRequest.FromString,
                    response_serializer=federation__pb2.AttributeQueryResponse.SerializeToString,
            ),
            'UploadGradients': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadGradients,
                    request_deserializer=federation__pb2.GradientChunk.FromString,
                    response_serializer=federation__pb2.UploadResponse.SerializeToString,
            ),
            'DownloadModel': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadModel,
                    request_deserializer=federation__pb2.ModelRequest.FromString,
                    response_serializer=federation__pb2.ModelChunk.SerializeToString,
            ),
            'SendElection': grpc.unary_unary_rpc_method_handler(
                    servicer.SendElection,
                    request_deserializer=federation__pb2.ElectionMessage.FromString,
                    response_serializer=federation__pb2.ElectionResponse.SerializeToString,
            ),
            'AnnounceCoordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceCoordinator,
                    request_deserializer=federation__pb2.CoordinatorMessage.FromString,
                    response_serializer=federation__pb2.CoordinatorAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federation.FederationCoordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('federation.FederationCoordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederationCoordinator:
    """Service gRPC du coordinateur d'apprentissage fédéré
    """

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federation.FederationCoordinator/RegisterClient',
            federation__pb2.RegisterRequest.SerializeToString,
            federation__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federation.FederationCoordinator/Heartbeat',
            federation__pb2.HeartbeatRequest.SerializeToString,
            federation__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestMutualExclusion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federation.FederationCoordinator/RequestMutualExclusion',
            federation__pb2.MutexRequest.SerializeToString,
            federation__pb2.MutexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseMutualExclusion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federation.FederationCoordinator/ReleaseMutualExclusion',
            federation__pb2.MutexRelease.SerializeToString,
            federation__pb2.MutexAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federation.FederationCoordinator/ResolveName',
            federation__pb2.NameResolveRequest.SerializeToString,
            federation__pb2.NameResolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryByAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federation.FederationCoordinator/QueryByAttributes',
            federation__pb2.AttributeQueryRequest.SerializeToString,
            federation__pb2.AttributeQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadGradients(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/federation.FederationCoordinator/UploadGradients',
            federation__pb2.GradientChunk.SerializeToString,
            federation__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/federation.FederationCoordinator/DownloadModel',
            federation__pb2.ModelRequest.SerializeToString,
            federation__pb2.ModelChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendElection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federation.FederationCoordinator/SendElection',
            federation__pb2.ElectionMessage.SerializeToString,
            federation__pb2.ElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnnounceCoordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federation.FederationCoordinator/AnnounceCoordinator',
            federation__pb2.CoordinatorMessage.SerializeToString,
            federation__pb2.CoordinatorAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
